
// Register user
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Christian",
    "surname": "Garico",
    "password": "123",
    "email": "no@email.it",
    "age": 31,
    "avatar": null,
    "role": "admin"
}
###

// Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ciao@example.com",
    "password": "123"
}

###

// Me

GET http://localhost:5000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZWIxNDc3ZDhjZTRiNjNjZjE4ODdlNyIsImlhdCI6MTcyNjY4MjU0MSwiZXhwIjoxNzI2NzY4OTQxfQ.8S2LwiFDG5HK4h-0o8EWYZVJUf8yp6rN4rhCPqsLG-4
